package furhatos.app.pacientehospital.nlu.entities

import furhatos.nlu.EnumEntity
import furhatos.util.Language

class Evento : EnumEntity() {
    override fun getEnum(lang: Language): List<String> {
        return listOf(
            "Comer",
            "Dormir",
            "Beber agua",
            "Bañarse",
            "Cepillarse los dientes",
            "Peinarse",
            "Vestirse",
            "Trabajar",
            "Estudiar",
            "Limpiar la casa",
            "Hacer la cama",
            "Cocinar",
            "Ir de compras",
            "Conducir",
            "Usar el transporte público",
            "Leer",
            "Ver televisión",
            "Escuchar música",
            "Hablar por teléfono",
            "Revisar las redes sociales",
            "Enviar mensajes de texto",
            "Cuidar de los niños",
            "Pasear al perro",
            "Alimentar a las mascotas",
            "Lavarse las manos",
            "Hacer ejercicio",
            "Meditar",
            "Practicar yoga",
            "Correr",
            "Caminar",
            "Nadar",
            "Andar en bicicleta",
            "Hacer estiramientos",
            "Practicar la respiración profunda",
            "Ir al gimnasio",
            "Practicar deportes",
            "Culturismo",
            "Hacer senderismo",
            "Hacer escalada",
            "Baile",
            "Pilates",
            "Tai chi",
            "Tomar vitaminas y suplementos",
            "Seguir una dieta saludable",
            "Hacer chequeos médicos regulares",
            "Planificar el día",
            "Hacer listas de tareas",
            "Usar una agenda",
            "Revisar el correo electrónico",
            "Participar en reuniones",
            "Tomar notas",
            "Establecer metas",
            "Realizar tareas de manera ordenada",
            "Hacer descansos regulares",
            "Organizar el espacio de trabajo",
            "Delegar tareas",
            "Gestionar el tiempo",
            "Aprender nuevas habilidades",
            "Leer libros de desarrollo personal",
            "Practicar la escritura",
            "Salir con amigos",
            "Tener citas",
            "Pasar tiempo en familia",
            "Jugar videojuegos",
            "Ver películas",
            "Ir al cine",
            "Ir a conciertos",
            "Asistir a eventos deportivos",
            "Participar en clubes",
            "Jugar juegos de mesa",
            "Viajar",
            "Acampar",
            "Hacer picnics",
            "Visitar museos",
            "Participar en festivales",
            "Hacer voluntariado",
            "Dibujar",
            "Pintar",
            "Escribir",
            "Leer libros",
            "Jardinería",
            "Cocinar nuevas recetas",
            "Hornear",
            "Tejer",
            "Hacer manualidades",
            "Tocar un instrumento musical",
            "Cantar",
            "Fotografía",
            "Hacer videos",
            "Bloguear",
            "Vloguear",
            "Pescar",
            "Cazar",
            "Practicar la astronomía",
            "Hacer modelismo",
            "Coleccionar objetos (sellos, monedas, etc.)",
            "Hacer puzzles",
            "Origami",
            "Jugar al ajedrez",
            "Hacer cerámica",
            "Participar en competiciones de esports",
            "Practicar el cosplay",
            "Crear software o videojuegos",
            "Hacer bricolaje",
            "Restaurar muebles",
            "Practicar la apicultura",
            "Crear jardineras y bonsáis",
            "Hacer enología (estudio y degustación de vinos)",
            "Participar en comunidades online",
            "Leer libros de autoayuda",
            "Asistir a talleres y seminarios",
            "Practicar la gratitud",
            "Llevar un diario",
            "Hacer visualizaciones",
            "Practicar afirmaciones positivas",
            "Participar en retiros espirituales",
            "Estudiar religiones y filosofías",
            "Participar en grupos de apoyo",
            "Realizar actos de bondad al azar",
            "Jugar al fútbol",
            "Jugar al baloncesto",
            "Jugar al tenis",
            "Jugar al voleibol",
            "Practicar el rugby",
            "Jugar al hockey",
            "Hacer esquí",
            "Hacer snowboard",
            "Patinaje sobre hielo",
            "Patinaje en línea",
            "Practicar el surf",
            "Practicar windsurf",
            "Practicar kitesurf",
            "Practicar paddle surf",
            "Remo",
            "Hacer piragüismo",
            "Hacer rafting",
            "Practicar el buceo",
            "Hacer snorkel",
            "Boxeo",
            "Kickboxing",
            "Jiu-jitsu",
            "Judo",
            "Karate",
            "Taekwondo",
            "Aikido",
            "Hapkido",
            "Capoeira",
            "Esgrima",
            "Tiro con arco",
            "Equitación",
            "Parapente",
            "Paracaidismo",
            "Salto base",
            "Escalada en roca",
            "Escalada en hielo",
            "Montañismo",
            "Escalada de interior",
            "Espeleología",
            "Orientación",
            "Crossfit",
            "Zumba",
            "Aeróbicos",
            "Spinning",
            "Esquí acuático",
            "Esquí de fondo",
            "Snowshoeing (raquetas de nieve)",
            "Parkour",
            "Gymnastics",
            "Trampolín",
            "Doma clásica",
            "Enduro",
            "Motocross",
            "Automovilismo",
            "Karting",
            "Paintball",
            "Airsoft",
            "Esgrima histórica",
            "Lucha libre",
            "Lucha grecorromana",
            "Lucha sambo",
            "Lanzamiento de jabalina",
            "Lanzamiento de disco",
            "Lanzamiento de martillo",
            "Salto con pértiga",
            "Salto de longitud",
            "Salto triple",
            "Atletismo (carreras)",
            "Marcha atlética",
            "Triatlón",
            "Duathlon",
            "Pentatlón",
            "Heptatlón",
            "Decatlón"
        )
    }
}