package furhatos.app.pacientehospital.nlu.entities

import furhatos.nlu.EnumEntity
import furhatos.util.Language

class Habito : EnumEntity() {
    override fun getEnum(lang: Language): List<String> {
        return listOf(
            "deporte: deporte, practicar deporte,practicas deporte,actividad fisica, actividad fisica",
            "trabajar: trabajar, trabajas, trabajo, trabaja",
            "alimentar: alimetar, alimentas",
            "Dormir:dormir,duermes, duerme",
            "actividades de ocio",
            "Beber agua:beber agua,bebes agua",
            "Asearse: asearse,bañarse,te bañas,bañarte,ducharte,asearte,te aseas",
            "Cepillarse los dientes: cepillarse los dientes,cepillarte los dientes,cepillar los dientes, cepilla los dientes",
            "lavarse las manos: lavarse las manos, lavarte las manos, te lavas las manos, se lava las manos",
            "Hacer chequeos médicos:hacer chequeos médicos,haces chequeos médicos",
            "Mantener buena postura: mantener buena postura, mantener una buena postura, mantienes una buena postura",
            "Ejercicios de estiramiento",
            "Ejercicios articulares",

            "estar en reposo: estar en reposo, estas en reposo",
            "estar sentado: estar sentado, estar sentada, estas sentado, estas sentada",
            "estar tumbado: estar tumbado, estar tumbada, estas tumbado, estas tumbada",
            "camirar: caminar, caminas",
            "correr: correr, corres",
            "subir escaleras: subir escaleras, subes escaleras",
            "esforzarse: esforzarse, hacer esfuerzo, haces esfuerzo, esfuerzas, te esfuerzas, haces esfuerzos, hace esfuerzos, esfuerzo, esfuerzos, esfuerzo fisico",
            "mover la articulacion: mover la articulacion, mover las articulaciones, hacer movimientos de articulaciones",
            "hablar: hablar, hablas",
            "reirse: reirse, se rie, te ries, reir",
            "orinar: orinar, mear, orinas, meas, orina, mea",
            "defecar: defecar, cagar, defecas, defeca, cagas, caga",
            "relaciones sexuales: sexo, intimas, relaciones sexuales, coito",
            "mover la lengua: mover la lengua, mueves la lengua",
            "Mover los brazos: Mover los brazos, mueves los brazos",
            "Mover las piernas: Mover las piernas, mueves las piernas",
            "Mover los dedos: Mover los dedos, mueves los dedos",
            "Mover los pies: Mover los pies, mueves los pies",
            "Mover la cabeza: Mover la cabeza, mueves la cabeza.",
            "Mover los hombros: Mover los hombros, mueves los hombros",
            "Mover las manos: Mover las manos, mueves las manos",
            "Mover los ojos: Mover los ojos, mueves los ojos",
            "Mover la cintura: Mover la cintura, mueves la cintura",
            "Mover las rodillas: Mover las rodillas, mueves las rodillas",
            "Mover los codos: Mover los codos, mueves los codos",
            "Mover los tobillos: Mover los tobillos, mueves los tobillos",
            "Mover los dedos de los pies: Mover los dedos de los pies, mueves los dedos de los pies",

            "Pantalla: pantalla, estar frente a una pantalla, estar frente a la pantalla, estas frente a una pantalla, estas frente a la pantalla",
            "cafe: cafe, tomar cafe, tomas cafe, consumir cafe, consumes cafe",

            "fumar:fumar,fumas",
            "drogas",
            "drogas por inyeccion",
            "entrenar",
            "tennis",
            "siesta: siesta, echar la siesta, echas la siesta, hacer siestas, tomar una siesta, tomas la siesta, tomas siestas",

            "Trabajar:trabajar,trabajas",
            "Estudiar:estudiar,estudias",
            "Limpiar la casa:limpiar la casa,limpias la casa",
            "Hacer la cama:hacer la cama,haces la cama",
            "Cocinar:cocinar,cocinas",
            "Ir de compras:ir de compras,vas de compras",
            "Conducir:conducir,conduces",
            "Usar el transporte público:usar el transporte público,usas el transporte público",
            "Leer:leer,lees",
            "Ver televisión:ver televisión,ves televisión",
            "Escuchar música:escuchar música,escuchas música",
            "Hablar por teléfono:hablar por teléfono,hablas por teléfono",
            "Revisar las redes sociales:revisar las redes sociales,revsas las redes sociales",
            "Lavarse las manos:lavarse las manos,te lavas las manos",
            "Hacer ejercicio:hacer ejercicio,haces ejercicio",
            "Meditar:meditar,meditas",
            "Practicar yoga:practicar yoga,practicas yoga",
            "Correr:correr,corres",
            "Caminar:caminar,caminas",
            "Nadar:nadar,nadas",
            "bicicleta:andar en bicicleta,andas en bicicleta, bicicleta",
            "Hacer estiramientos:hacer estiramientos,haces estiramientos",
            "Practicar la respiración profunda:practicar la respiración profunda,practicas la respiración profunda",
            "Ir al gimnasio:ir al gimnasio,vas al gimnasio",
            "Hacer senderismo:hacer senderismo,haces senderismo",
            "Hacer escalada:hacer escalada,haces escalada",
            "Baile:baile,bailas",
            "pilates",
            "tai chi",
            "Planificar el día:planificar el día,planificas el día",
            "Hacer listas de tareas:hacer listas de tareas,haces listas de tareas",
            "Usar una agenda:usar una agenda,usas una agenda",
            "Participar en reuniones:participar en reuniones,participas en reuniones",
            "metas:establecer metas,estableces metas, tienes metas",
            "descansar :hacer descansos, haces descansos, descansas, descansar",
            "Organizar el espacio de trabajo:organizar el espacio de trabajo,organizas el espacio de trabajo, organizar tu espacio de trabajo,organizas tu espacio de trabajo",
            "Aprender nuevas habilidades:aprender nuevas habilidades,aprendes nuevas habilidades, aprender habilidades nuevas,aprendes habilidades nuevas",
            "Aprender nuevas cosas:aprender nuevas cosas,aprendes nuevas cosas, aprender cosas nuevas,aprendes cosas nuevas",
            "escribir: escribir,escribes",
            "Salir con amigos:salir con amigos,sales con amigos",
            "Tener citas:tener citas,tienes citas",
            "Pasar tiempo en familia:pasar tiempo en familia,pasas tiempo en familia",
            "Jugar videojuegos:jugar videojuegos,juegas videojuegos",
            "Ir al cine:ir al cine,vas al cine",
            "Ir a conciertos:ir a conciertos",
            "Jugar juegos de mesa:jugar juegos de mesa,juegas juegos de mesa",
            "Viajar:viajar,viajas",
            "Acampar:acampar,acampas",
            "Dibujar:dibujar,dibujas",
            "Pintar:pintar,pintas",
            "Leer:leer,lees ",
            "Cantar:cantar,cantas",
            "Fotografía:fotografía,fotografías",
            "Bloguear:bloguear,blogueas",
            "Pescar:pescar,pescas",
            "Cazar:cazar,cazas",
            "Hacer puzzles:hacer puzzles,haces puzzles",
            "Jugar al ajedrez:jugar al ajedrez,juegas al ajedrez",
            "Practicar la gratitud:practicar la gratitud,practicas la gratitud",
            "Llevar un diario:llevar un diario,llevas un diario, journaling",
            "fútbol: futbol,jugar al fútbol,juegas al fútbol",
            "baloncesto:baloncesto,jugar a baloncesto, juegas al baloncesto",
            "voleibol:voleibol,jugar al voleibol,juegas al voleibol",
            "rugby:rugby,practicar el rugby,practicas el rugby",
            "Hacer esquí:hacer esquí,haces esquí",
            "Hacer snowboard:hacer snowboard,haces snowboard",
            "patinar: patinar, patinas",

        )
    }
}