package furhatos.app.pacientehospital.nlu.entities

import furhatos.nlu.EnumEntity
import furhatos.util.Language

class Habito : EnumEntity() {
    override fun getEnum(lang: Language): List<String> {
        return listOf(
            "fumar:fumar,fumas",
            "drogas",
            "cocaína",
            "drogas por inyeccion",
            "Deporte",
            "nadar",
            "entrenar",
            "actividad fisica",
            "tennis",
            "actividades de ocio",
            "dormir: dormir, duermes, duerme",
            "siesta",
            "trabajar: trabajar, trabajas, trabajo, trabaja",
            "Comer:comer,comes",
            "Dormir:dormir,duermes",
            "Beber agua:beber agua,bebes agua",
            "Bañarse:bañarse,te bañas,bañarte,bañar",
            "Cepillarse los dientes:cepillarse los dientes,cepillarte los dientes,cepillar los dientes",
            "Peinarse:peinarse,peinar,peinarte",
            "Vestirse:vestirse,vestir,vestirte",
            "Trabajar:trabajar,trabajas",
            "Estudiar:estudiar,estudias",
            "Limpiar la casa:limpiar la casa,limpias la casa",
            "Hacer la cama:hacer la cama,haces la cama",
            "Cocinar:cocinar,cocinas",
            "Ir de compras:ir de compras,vas de compras",
            "Conducir:conducir,conduces",
            "Usar el transporte público:usar el transporte público,usas el transporte público",
            "Leer:leer,lees",
            "Ver televisión:ver televisión,ves televisión",
            "Escuchar música:escuchar música,escuchas música",
            "Hablar por teléfono:hablar por teléfono,hablas por teléfono",
            "Revisar las redes sociales:revisar las redes sociales,revsas las redes sociales",
            "Enviar mensajes de texto:enviar mensajes de texto,envías mensajes de texto",
            "Cuidar de los niños:cuidar de los niños,cuidas de los niños",
            "Pasear al perro:pasear al perro,paseas al perro",
            "Alimentar a las mascotas:alimentar a las mascotas,alimentas a las mascotas",
            "Lavarse las manos:lavarse las manos,te lavas las manos",
            "Hacer ejercicio:hacer ejercicio,haces ejercicio",
            "Meditar:meditar,meditas",
            "Practicar yoga:practicar yoga,practicas yoga",
            "Correr:correr,corres",
            "Caminar:caminar,caminas",
            "Nadar:nadar,nadas",
            "Andar en bicicleta:andar en bicicleta,andas en bicicleta",
            "Hacer estiramientos:hacer estiramientos,haces estiramientos",
            "Practicar la respiración profunda:practicar la respiración profunda,practicas la respiración profunda",
            "Ir al gimnasio:ir al gimnasio,vas al gimnasio",
            "Practicar deportes:practicar deportes,practicas deportes",
            "Culturismo:culturismo,culturismo",
            "Hacer senderismo:hacer senderismo,haces senderismo",
            "Hacer escalada:hacer escalada,haces escalada",
            "Baile:baile,bailas",
            "Pilates:pilates,pilates",
            "Tai chi:tai chi,tai chi",
            "Tomar vitaminas y suplementos:tomar vitaminas y suplementos,tomas vitaminas y suplementos",
            "Seguir una dieta saludable:seguir una dieta saludable,sigues una dieta saludable",
            "Hacer chequeos médicos regulares:hacer chequeos médicos regulares,haces chequeos médicos regulares",
            "Planificar el día:planificar el día,planificas el día",
            "Hacer listas de tareas:hacer listas de tareas,haces listas de tareas",
            "Usar una agenda:usar una agenda,usas una agenda",
            "Revisar el correo electrónico:revisar el correo electrónico,revsas el correo electrónico",
            "Participar en reuniones:participar en reuniones,participas en reuniones",
            "Tomar notas:tomar notas,tomas notas",
            "Establecer metas:establecer metas,estableces metas",
            "Realizar tareas de manera ordenada:realizar tareas de manera ordenada,realizas tareas de manera ordenada",
            "Hacer descansos regulares:hacer descansos regulares,haces descansos regulares",
            "Organizar el espacio de trabajo:organizar el espacio de trabajo,organizas el espacio de trabajo",
            "Delegar tareas:delegar tareas,delegas tareas",
            "Gestionar el tiempo:gestionar el tiempo,gestionas el tiempo",
            "Aprender nuevas habilidades:aprender nuevas habilidades,aprendes nuevas habilidades",
            "Leer libros de desarrollo personal:leer libros de desarrollo personal,lees libros de desarrollo personal",
            "Practicar la escritura:practicar la escritura,practicas la escritura",
            "Salir con amigos:salir con amigos,sales con amigos",
            "Tener citas:tener citas,tienes citas",
            "Pasar tiempo en familia:pasar tiempo en familia,pasas tiempo en familia",
            "Jugar videojuegos:jugar videojuegos,juegas videojuegos",
            "Ver películas:ver películas,ves películas",
            "Ir al cine:ir al cine,vas al cine",
            "Ir a conciertos:ir a conciertos",
            "Asistir a eventos deportivos:asistir a eventos deportivos,asistes a eventos deportivos",
            "Participar en clubes:participar en clubes,participas en clubes",
            "Jugar juegos de mesa:jugar juegos de mesa,juegas juegos de mesa",
            "Viajar:viajar,viajas",
            "Acampar:acampar,acampas",
            "Hacer picnics:hacer picnics,haces picnics",
            "Visitar museos:visitar museos,visitas museos",
            "Participar en festivales:participar en festivales,participas en festivales",
            "Hacer voluntariado:hacer voluntariado,haces voluntariado",
            "Dibujar:dibujar,dibujas",
            "Pintar:pintar,pintas",
            "Escribir:escribir,escribes",
            "Leer libros:leer libros,lees libros",
            "Jardinería:jardinería,jardineas",
            "Cocinar nuevas recetas:cocinar nuevas recetas,cocinas nuevas recetas",
            "Hornear:hornear,horneas",
            "Tejer:tejer,tejes",
            "Hacer manualidades:hacer manualidades,haces manualidades",
            "Tocar un instrumento musical:tocar un instrumento musical,tocas un instrumento musical",
            "Cantar:cantar,cantas",
            "Fotografía:fotografía,fotografías",
            "Hacer videos:hacer videos,haces videos",
            "Bloguear:bloguear,blogueas",
            "Vloguear:vloguear,vlogueas",
            "Pescar:pescar,pescas",
            "Cazar:cazar,cazas",
            "Practicar la astronomía:practicar la astronomía,practicas la astronomía",
            "Hacer modelismo:hacer modelismo,haces modelismo",
            "Coleccionar objetos (sellos, monedas, etc.):coleccionar objetos (sellos, monedas, etc.),coleccionas objetos (sellos, monedas, etc.)",
            "Hacer puzzles:hacer puzzles,haces puzzles",
            "Origami:origami,haces origami",
            "Jugar al ajedrez:jugar al ajedrez,juegas al ajedrez",
            "Hacer cerámica:hacer cerámica,haces cerámica",
            "Participar en competiciones de esports:participar en competiciones de esports,participas en competiciones de esports",
            "Practicar el cosplay:practicar el cosplay,practicas el cosplay",
            "Crear software o videojuegos:crear software o videojuegos,creas software o videojuegos",
            "Hacer bricolaje:hacer bricolaje,haces bricolaje",
            "Restaurar muebles:restaurar muebles,restauras muebles",
            "Practicar la apicultura:practicar la apicultura,practicas la apicultura",
            "Crear jardineras y bonsáis:crear jardineras y bonsáis,creas jardineras y bonsáis",
            "Hacer enología (estudio y degustación de vinos):hacer enología (estudio y degustación de vinos),haces enología (estudio y degustación de vinos)",
            "Participar en comunidades online:participar en comunidades online,participas en comunidades online",
            "Leer libros de autoayuda:leer libros de autoayuda,lees libros de autoayuda",
            "Asistir a talleres y seminarios:asistir a talleres y seminarios,asistes a talleres y seminarios",
            "Practicar la gratitud:practicar la gratitud,practicas la gratitud",
            "Llevar un diario:llevar un diario,llevas un diario",
            "Hacer visualizaciones:hacer visualizaciones,haces visualizaciones",
            "Practicar afirmaciones positivas:practicar afirmaciones positivas,practicas afirmaciones positivas",
            "Participar en retiros espirituales:participar en retiros espirituales,participas en retiros espirituales",
            "Estudiar religiones y filosofías:estudiar religiones y filosofías,estudias religiones y filosofías",
            "Participar en grupos de apoyo:participar en grupos de apoyo,participas en grupos de apoyo",
            "Realizar actos de bondad al azar:realizar actos de bondad al azar,realizas actos de bondad al azar",
            "Jugar al fútbol:jugar al fútbol,juegas al fútbol",
            "Jugar al baloncesto:jugar a baloncesto, juegas al baloncesto",
            "Jugar al tenis:jugar al tenis,juegas al tenis",
            "Jugar al voleibol:jugar al voleibol,juegas al voleibol",
            "Practicar el rugby:practicar el rugby,practicas el rugby",
            "Jugar al hockey:jugar al hockey,juegas al hockey",
            "Hacer esquí:hacer esquí,haces esquí",
            "Hacer snowboard:hacer snowboard,haces snowboard",
            "Patinaje sobre hielo:patinaje sobre hielo,patinas sobre hielo",
            "Patinaje en línea:patinaje en línea,patinas en línea",
            "Practicar el surf:practicar el surf,practicas el surf",
            "Practicar windsurf:practicar windsurf,practicas windsurf",
            "Practicar kitesurf:practicar kitesurf,practicas kitesurf",
            "Practicar paddle surf:practicar paddle surf,practicas paddle surf",
            "Remo:remo,remas",
            "Hacer piragüismo:hacer piragüismo,haces piragüismo",
            "Hacer rafting:hacer rafting,haces rafting",
            "Practicar el buceo:practicar el buceo,practicas el buceo",
            "Hacer snorkel:hacer snorkel,haces snorkel",
            "Boxeo:boxeo,boxeas",
            "Kickboxing:kickboxing,kickboxeas",
            "Jiu-jitsu:jiu-jitsu,practicas jiu-jitsu",
            "Judo:judo,practicas judo",
            "Karate:karate,practicas karate",
            "Taekwondo:taekwondo,practicas taekwondo",
            "Aikido:aikido,practicas aikido",
            "Hapkido:hapkido,practicas hapkido",
            "Capoeira:capoeira,practicas capoeira",
            "Esgrima:esgrima,practicas esgrima",
            "Tiro con arco:tiro con arco,practicas tiro con arco",
            "Equitación:equitación,practicas equitación",
            "Parapente:parapente,practicas parapente",
            "Paracaidismo:paracaidismo,practicas paracaidismo",
            "Salto base:salto base,practicas salto base",
            "Escalada en roca:escalada en roca,escalas en roca",
            "Escalada en hielo:escalada en hielo,escalas en hielo",
            "Montañismo:montañismo,practicas montañismo",
            "Escalada de interior:escalada de interior,escalas de interior",
            "Espeleología:espeleología,practicas espeleología",
            "Orientación:orientación,practicas orientación",
            "Crossfit:crossfit,practicas crossfit",
            "Zumba:zumba,practicas zumba",
            "Aeróbicos:aeróbicos,practicas aeróbicos",
            "Spinning:spinning,practicas spinning",
            "Esquí acuático:esquí acuático,practicas esquí acuático",
            "Esquí de fondo:esquí de fondo,practicas esquí de fondo",
            "Snowshoeing (raquetas de nieve):snowshoeing (raquetas de nieve),practicas snowshoeing (raquetas de nieve)",
            "Parkour:parkour,practicas parkour",
            "Gymnastics:gymnastics,practicas gymnastics",
            "Trampolín:trampolín,practicas trampolín",
            "Doma clásica:doma clásica,practicas doma clásica",
            "Enduro:enduro,practicas enduro",
            "Motocross:motocross,practicas motocross",
            "Automovilismo:automovilismo,practicas automovilismo",
            "Karting:karting,practicas karting",
            "Paintball:paintball,juegas paintball",
            "Airsoft:airsoft,juegas airsoft",
            "Esgrima histórica:esgrima histórica,practicas esgrima histórica",
            "Lucha libre:lucha libre,practicas lucha libre",
            "Lucha grecorromana:lucha grecorromana,practicas lucha grecorromana",
            "Lucha sambo:lucha sambo,practicas lucha sambo",
            "Lanzamiento de jabalina:lanzamiento de jabalina,practicas lanzamiento de jabalina",
            "Lanzamiento de disco:lanzamiento de disco,practicas lanzamiento de disco",
            "Lanzamiento de martillo:lanzamiento de martillo,practicas lanzamiento de martillo",
            "Salto con pértiga:salto con pértiga,practicas salto con pértiga",
            "Salto de longitud:salto de longitud,practicas salto de longitud",
            "Salto triple:salto triple,practicas salto triple",
            "Atletismo (carreras):atletismo (carreras),practicas atletismo (carreras)",
            "Marcha atlética:marcha atlética,practicas marcha atlética",
            "Triatlón:triatlón,practicas triatlón",
            "Duatlón:duatlón,practicas duatlón",
            "Pentatlón:pentatlón,practicas pentatlón",
            "Heptatlón:heptatlón,practicas heptatlón",
            "Decatlón:decatlón,practicas decatlón"
        )
    }
}