package furhatos.app.pacientehospital.nlu.entities

import furhatos.nlu.EnumEntity
import furhatos.util.Language

class Alimento : EnumEntity() {
    override fun getEnum(lang: Language): List<String> {
        return listOf(
            "Proteínas",
            "Carbohidratos",
            "Grasas",
            "Fibra dietética",
            "Vitaminas",
            "Minerales",
            "Agua",
            "Ácidos grasos",
            "Antioxidantes",
            "Aminoácidos esenciales",
            "Sal",
            "Azucar",
            "Agua",
            "Micronutrientes",


            "verduras",
            "alcohol",
            "vino",
            "aditivos alimentarios",
            "patatas",
            "nutrientes",
            "chocolate",
            "comida rapida",
            "agua",
            "judias",
            "comida picante",
            "frutos secos",

            "abadejo",
            "abulón",
            "acedias fritas",
            "aceite de almendras",
            "aceite de cacahuete",
            "aceite de coco",
            "aceite de girasol",
            "aceite de maíz",
            "aceite de nuez",
            "aceite de oliva",
            "aceite de sésamo",
            "aceite de soja",
            "aceite Uva",
            "aceitunas negras",
            "aceitunas verdes",
            "acelga cruda",
            "acerolas",
            "agua carbonatada",
            "agua Manantial",
            "aguacate crudo",
            "ajo crudo",
            "albahaca cruda",
            "albaricoque crudo",
            "albaricoque en almíbar ",
            "albaricoque crudo: albaricoque crudo, albaricoque seco",
            "albóndigas suecas con crema o salsa blanca",
            "alcachofa, cocida, enlatada, hecha con aceite",
            "alcachofa, cocida, fresca, hecha con aceite",
            "alcachofas",
            "alitas de pollo",
            "almejas",
            "almendras saladas",
            "almendras sin sal",
            "almendras sin tostar",
            "alubias blancas",
            "anacardos",
            "ancas de rana",
            "anchoa enlatada",
            "anguila",
            "anguila ahumada",
            "anguila al vapor o escalfada",
            "angulas",
            "anisete",
            "apio cocido",
            "apio crudo",
            "arándanos",
            "arándanos secos",
            "arenque crudo",
            "arenque Seco",
            "arenque",
            "arroz cocido con leche",
            "arroz integral",
            "arroz  Blanco",
            "buñuelos franceses",
            "buñuelos de plátano",
            "buñuelos de bacalao",
            "buñuelos de maíz",
            "burrito de carne",
            "burrito de pollo",
            "burrito",
            "butifarra",
            "caballa ahumada",
            "caballa cruda",
            "caballa enlatada",
            "cacahuetes",
            "cacahuetes salados",
            "cacahuetes tostados",
            "cacao en polvo",
            "café",
            "café capuchino",
            "café cubano",
            "café descafeinado",
            "café expreso",
            "café expreso descafeinado",
            "café extracto, polvo",
            "café infusión",
            "café instantáneo (soluble en polvo)",
            "café irlandés",
            "café torrefacto",
            "café, café con leche",
            "café, café con leche, descafeinado",
            "calabacín",
            "calabaza",
            "calamar crudo",
            "calamares enlatados",
            "caldo de pescado",
            "caldo de pollo: caldo de pollo, caldo de pavo",
            "caldo de verduras",
            "callos",
            "calzone",
            "camarones",
            "canelones",
            "cangrejo",
            "cangrejo de mar",
            "cangrejo de río",
            "cangrejo enlatado",
            "caquis",
            "caracoles",
            "cardo",
            "carne de caballo: carne de caballo, caballo",
            "carne de cabra: carne de cabra, cabra",
            "carne cabrito: carne de cabrito, cabrito",
            "carne de cerdo: carne de cerdo, cerdo",
            "carne de conejo: carne de conejo, conejo",
            "carne de cordero: carne de cordero, cordero",
            "carne de res: carne de res, res",
            "carne de venado: carne de venado: venado",
            "carne de oveja: carne de oveja, oveja",
            "carne de ternera: cane de ternera, ternera",
            "carne de vaca: carne de vaca, vaca",
            "carne de pescado: carne de pescado, pescado",
            "carne de pescado blanco: carne de pescado blanco, pescado blanco",
            "carne de pescado azul: carne de pescado azul, pescado azul",
            "carne de pato: carne de pato, pato",
            "carne de pavo: carne de pavo, pavo",
            "carne de pollo: carne de pollo, pollo",
            "carpa",
            "castañas",
            "caviar",
            "cebada",
            "cebolla",
            "cebollino crudo",
            "centollo",
            "cereales",
            "cerales blancos",
            "cereales integrales",
            "cereales de chocolate",
            "cereales de arroz: cereales de arroz, cereales de arroz inflado",
            "cereales de avena",
            "cereales de trigo",
            "cereales de maiz",
            "cerezas",
            "cerveza",
            "cerveza clara",
            "cerveza oscura",
            "ceviche",
            "champán",
            "champiñones",
            "champiñones crudos",
            "champiñones cocinados",
            "chanquetes",
            "chícharos: chicharros, chicharrones",
            "chile con frijoles sin carne",
            "chili",
            "chirimoya",
            "chirivías",
            "chocolate blanco",
            "chocolate blanco con almendras",
            "chocolate con leche",
            "chocolate negro: chocolate negro, chocolate oscuro",
            "chocolate negro con almendras: chocolate negro con almendras, chocolate oscuro con almendras",
            "chorizo",
            "churros",
            "cigala",
            "cilantro",
            "ciruela",
            "coco",
            "carne codorniz: carne codorniz, codorniz",
            "col",
            "coles de bruselas",
            "coliflor",
            "congro",
            "conguitos",
            "coñac",
            "cortezas de piel de cerdo",
            "crep",
            "croissant",
            "croissant, queso",
            "croqueta de jamón",
            "cuajada",
            "cubitos sopa",
            "daiquiri",
            "dátiles",
            "diente de león verde, crudo",
            "dorada",
            "emperador",
            "emperador a la plancha",
            "encurtidos, mezclados",
            "endibias",
            "ensalada césar de pollo o pavo lechuga, tomate, queso, sin aderezo",
            "ensalada césar, con lechuga romana, sin aderezo",
            "ensalada de atún con huevo",
            "ensalada de atún con queso",
            "espárragos cocinados: esparragos cocidos, esparragos cocinados",
            "espárragos",
            "espinacas",
            "flanes de huevo",
            "foie-gras",
            "frambuesas",
            "fresas",
            "frijoles",
            "galletas",
            "galletas de mantequilla",
            "galletas de jengibre",
            "galletas de almendra",
            "galletas de avena",
            "galletas con pasas",
            "galletas saladas",
            "gambas",
            "gambas cocinadas: gambas cocinadas, gambas cocidas",
            "garbanzos",
            "bebidas energeticas",
            "bebidas con cafeina",
            "gazpacho",
            "gin tonic",
            "ginebra",
            "gofio de millo",
            "gofio de trigo",
            "granada",
            "grosellas",
            "guisantes",
            "habas",
            "hamburguesa: hamburgesa, hamburgesas",
            "hamburguesa de ternera",
            "hamburguesa de pollo",
            "hamburguesa de pescado",
            "hamburguesa vegana: hamburgesa vegana, hamburgesas veganas",
            "harina de avena",
            "harina de centeno",
            "harina de maíz",
            "harina de soja",
            "harina de trigo integral",
            "harina trigo",
            "helado",
            "hígado de cerdo",
            "hígado depollo",
            "hígado de ternera",
            "higos",
            "huevas de arenque",
            "huevas de esturión",
            "huevos",
            "huevo crudo: huevo crudo, huevos crudos",
            "huevo frito: huevo frito, huevos frito",
            "huevo cocido: huevo cocido, huevos cocidos",
            "llema de huevo: llema de huevo, llemas de huevo",
            "clara de huevo: clara de huevo, clara de huevo",
            "hummus",
            "zumo: zumo, zumos",
            "kétchup",
            "kiwi",
            "langosta",
            "langostino",
            "leche semidesnatada",
            "leche desnatada",
            "leche entera",
            "leche de almendras",
            "leche de arroz",
            "leche de cabra",
            "leche de coco",
            "leche de soja",
            "leche sin lactosa",
            "lechuga",
            "lentejas",
            "levadura",
            "lima",
            "limón",
            "lomo cerdo",
            "lubina",
            "lucio",
            "macarrones",
            "magdalenas",
            "bolleria industrial",
            "maíz",
            "malvaviscos",
            "mandarina",
            "mango",
            "manteca de cerdo",
            "mantequilla",
            "manzana",
            "margarina",
            "martini",
            "mayonesa",
            "mazapán",
            "mejillones",
            "mejillones cocinados",
            "melocotón",
            "melocotón en almíbar",
            "melón",
            "membrillo",
            "merluza",
            "mermelada",
            "miel",
            "miso",
            "molleja",
            "moras",
            "morcilla",
            "mortadela",
            "mostaza",
            "embutido: embutido, embutidos",
            "muslo de pollo",
            "nabo crudo",
            "nachos",
            "naranja",
            "nectarina",
            "nueces",
            "nuggets de pollo",
            "ñoquis",
            "cartilago de cerdo",
            "ostras",
            "paella de marisco",
            "paella de carne",
            "paloma",
            "palometa",
            "palomitas",
            "pan",
            "pan blanco",
            "pan de centeno",
            "pan de nuez",
            "pan integral",
            "pan multigrano",
            "pan de pita",
            "pan sin gluten",
            "papaya",
            "pasta",
            "pasta integral",
            "pasta sin gluten",
            "pastrami",
            "patata: patata, patatas",
            "patata asada: patata asada, patatas asadas",
            "patatas fritas",
            "pepinillo: pepinillo, pepinillos",
            "pepino: pepino, pepinos",
            "pera",
            "percebes",
            "carne de perdiz: carne de perdiz, perdiz",
            "perejil crudo",
            "pescadilla",
            "pez espada",
            "pichón",
            "pimiento: pimiento, pimientos",
            "pimiento crudo: pimiento crudo, pimientos crudos",
            "pimiento a la plancha: pimiento al la plancha, pimientos a la plancha",
            "pimientos en vinagre",
            "piña colada",
            "piña",
            "piña en almíbar",
            "piñones",
            "pipas",
            "pipas de girasol",
            "pistachos",
            "plátano",
            "pomelo",
            "Ponche",
            "gelatina: gelatina, gelatinas",
            "pretzel",
            "puerro",
            "pulpo",
            "queso",
            "queso azul",
            "queso blanco",
            "queso brie",
            "queso de cabra",
            "queso Cheddar",
            "queso feta",
            "queso fresco batido",
            "rábano",
            "rabo",
            "rabo de toro",
            "rape",
            "ratatouille",
            "raviolis",
            "cocacola",
            "cocacola cero",
            "golosina: golosina, golosinas, chuches, gominolas",
            "regaliz: regaliz, regalices",
            "remolachas",
            "repollo",
            "requesón",
            "riñón: riñon, riñones",
            "rodaballo",
            "ron",
            "sal",
            "salami",
            "salchichas Cerdo",
            "salchichas Fráncfort",
            "salchichón",
            "salmón cocinado: salmon cocinado, salmon ahumado",
            "salmón crudo: salmon crudo, sasimi",
            "salsa boloñesa",
            "salsa César",
            "salsa de Ajo",
            "salsa de arándano y frambuesa",
            "salsa de barbacoa",
            "salsa de cebolla",
            "salsa de chocolate",
            "salsa de ciruela",
            "salsa de cóctel",
            "salsa de enchilada roja",
            "salsa de enchilada, verde",
            "salsa de eneldo",
            "salsa de miel y mostaza",
            "salsa de pescado",
            "salsa de queso",
            "salsa de queso azul o roquefort",
            "salsa de soja",
            "salsa de tomate",
            "salsa de yogurt",
            "salsa holandesa",
            "salsa kétchup",
            "salsa pesto",
            "salsa tártara",
            "salsa teriyaki",
            "salsa tzatziki",
            "salsa verde o salsa verde",
            "sandía",
            "sangre de vacuno",
            "sangria",
            "sangría blanca",
            "sangría roja",
            "sardinas",
            "sardinas cocinadas",
            "sardinas enlatadas",
            "semillas de chía",
            "semillas de girasol",
            "semillas de sésamo",
            "sémola",
            "sepia",
            "sesos de cerdo",
            "sesos de cordero",
            "sesos de ternera",
            "setas: setas, hongos",
            "setas boletus: setas boletus, boletus",
            "setas cantharellus",
            "setas colmenilla",
            "refrescos con gas, refrescos con gas, refrescos gaseosos",
            "sidra de manzana",
            "sopa de cebolla",
            "sopa de pollo",
            "sopa de pescado",
            "sushi",
            "sushi con atún",
            "sushi con salmón",
            "tapioca",
            "tarta: tarta, tartas",
            "tarta manzana",
            "te",
            "té de hierbas",
            "té de manzanilla",
            "té verde",
            "tequila",
            "tocino",
            "tomate frito",
            "tomate triturado",
            "tomate: tomate, tomates",
            "tónica",
            "tortilla",
            "trucha",
            "trufas",
            "turrón",
            "uvas",
            "vermut",
            "vieiras",
            "vinagre",
            "vinagre de manzana",
            "vodka",
            "whisky",
            "yogurt",
            "yogur griego",
            "yogurt liquido: yogurt liquido, yogurt de beber",
            "yuca",
            "zanahoria: zanahoria, zanaorias",
            "zanahorias cocinadas"



        )
    }
}