package furhatos.app.pacientehospital.utils
/*
class EntityHelper {

    fun obtenerTermino(entrada: String): String {
        return when (entrada) {

            // SINTOMAS
            "herida", "heridas" -> "herida"
            "dolor", "dolores", "daño" -> "dolor"
            "debilidad muscular", "debilidad" -> "debilidad"
            "problema de equilibrio", "falta de equilibrio", "problemas de equilibrio" -> "falta de equilibrio"
            "fiebre", "dolor de cabeza", "dolores de cabeza" -> "fiebre"
            "sudor nocturno", "sudores nocturnos" -> "sudor nocturno"
            "cambios sensoriales", "cambio sensorial" -> "cambios sensoriales"
            "sibilancia", "sibilancias" -> "sibilancia"
            "mareo", "vertigo" -> "mareo"
            "vomito", "vomitos", "nauseas" -> "vomito"
            "problema urinario", "problemas urinarios" -> "problema urinario"
            "dolor articular", "dolor en las articulaciones" -> "dolor articular"
            "cambio de temperatura", "cambios de temperatura" -> "cambio de temperatura"
            "confusion", "cambios de memoria" -> "confusion"
            "mareo", "mareos" -> "mareo"
            "síncope", "sincopes" -> "síncope"
            "vértigo", "vertigos" -> "vértigo"
            "cambios de animo", "cambio de animo", "cambio de humor", "cambios de humor" -> "cambios en el estado mental"
            "respiracion dificultosa", "dificultad respiratoria", "dificultades respiratorias" -> "respiración dificultosa"
            "sentimiento suicida", "sentimientos suicida" -> "sentimiento suicida"
            "sentimiento desesperanza", "desesperanza" -> "sentimiento de desesperanza"
            "llanto", "llantos" -> "llanto"
            "desmayo", "desmayos" -> "desmayo"
            "estado de animo deprimido", "depresion", "deprimido" -> "estado de ánimo deprimido"
            "aumento de energia", "aumentos de energia", "subidon de energia", "subidones de enrgia" -> "aumento de energía"
            "desconcentracion", "incapacidad para concentrarse" -> "desconcentracion"
            "fatiga", "cansancio" -> "fatiga"
            "bajada de peso", "bajadas de peso", "disminucion del peso", "disminución del peso corporal" -> "bajada de peso"
            "hipotonia muscular", "bajada muscular" -> "hipotonía muscular"
            "quemazon", "sensación de quemazón" -> "quemazon"
            "cólico abdominal", "colico abdominal", "colicos abdominales" -> "cólico abdominal"
            "midrasis", "pupilas dilatadas" -> "midriasis"
            "incontinencia urinaria de urgencia", "urgencias orinarias", "incontinencia urinaria", "incontinencia de urgencia" -> "incontinencia urinaria de urgencia"
            "disminucion de heces", "calibre disminuido de las heces" -> "disminucion de heces"
            "heces amarillas", "heces amarillentas", "color amarillo en las heces", "color amarillento en las heces", "Color de las heces amarillo" -> "heces amarillas"
            "sofoco", "sofocos" -> "sofoco"
            "dolor subito", "dolores subitos" -> "dolor subito"
            "zumbido en los oidos", "zumbidos en los oidos" -> "zumbido en los oídos"
            "calambres", "calambre" -> "calambres"
            "ahogo", "ahogamiento" -> "ahogo"
            "estornudos", "estornudos", "estornudo" -> "estornudos"
            "flatulencias", "flatulencia", "flatulencias" -> "flatulencias"


            // ZONAS
            "cara", "rostro" -> "cara"
            "ojos", "ojo" -> "ojos"
            "dientes", "diente" -> "dientes"
            "orejas", "oreja" -> "orejas"
            "hombros", "hombro" -> "hombros"
            "columna vertebral", "columna" -> "columna vertebral"
            "trapecio", "trapecios" -> "trapecio"
            "brazo", "brazos", "extremidades superiores" -> "brazo"
            "mano", "manos" -> "mano"
            "dedos", "dedo" -> "dedos"
            "piernas", "pierna", "extremidades inferiores" -> "piernas"
            "pulmones", "pulmón" -> "pulmones"
            "dedos", "dedo" -> "dedos"
            "pulgar", "dedo pulgar" -> "pulgar"
            "índice", "dedo índice" -> "índice"
            "medio", "dedo medio" -> "medio"
            "anular", "dedo anular" -> "anular"
            "meñique", "dedo meñique" -> "meñique"
            "uñas", "uña" -> "uñas"
            "pie", "pies" -> "pie"

            // ALIMENTOS
            "carne de caballo", "caballo" -> "carne de caballo"
            "carne de cabra", "cabra" -> "carne de cabra"
            "carne cabrito", "cabrito" -> "carne cabrito"
            "carne de cerdo", "cerdo" -> "carne de cerdo"
            "carne de conejo", "conejo" -> "carne de conejo"
            "carne de cordero", "cordero" -> "carne de cordero"
            "carne de res", "res" -> "carne de res"
            "carne de venado", "venado" -> "carne de venado"
            "carne de oveja", "oveja" -> "carne de oveja"
            "carne de ternera", "ternera" -> "carne de ternera"
            "carne de vaca", "vaca" -> "carne de vaca"
            "carne de pescado", "pescado" -> "carne de pescado"
            "carne de pescado blanco", "pescado blanco" -> "carne de pescado blanco"
            "carne de pescado azul", "pescado azul" -> "carne de pescado azul"
            "carne de pato", "pato" -> "carne de pato"
            "carne de pavo", "pavo" -> "carne de pavo"
            "carne de pollo", "pollo" -> "carne de pollo"
            "caldo de pollo", "caldo de pavo" -> "caldo de pollo"
            "cereales de arroz", "cereales de arroz inflado" -> "cereales de arroz"
            "chícharos", "chicharrones" -> "chícharos"
            "chocolate negro", "chocolate oscuro" -> "chocolate negro"
            "chocolate negro con almendras", "chocolate oscuro con almendras" -> "chocolate negro con almendras"
            "carne codorniz", "codorniz" -> "carne codorniz"
            "espárragos cocinados", "espárragos cocidos" -> "espárragos cocinados"
            "gambas cocinadas", "gambas cocidas" -> "gambas cocinadas"
            "hamburguesa", "hamburguesas" -> "hamburguesa"
            "hamburguesa vegana", "hamburguesas veganas" -> "hamburguesa vegana"
            "huevo crudo", "huevos crudos" -> "huevo crudo"
            "huevo frito", "huevos fritos" -> "huevo frito"
            "huevo cocido", "huevos cocidos" -> "huevo cocido"
            "yema de huevo", "yemas de huevo" -> "yema de huevo"
            "clara de huevo", "claras de huevo" -> "clara de huevo"
            "zumo", "zumos" -> "zumo"
            "embutido", "embutidos" -> "embutido"
            "patata", "patatas" -> "patata"
            "patata asada", "patatas asadas" -> "patata asada"
            "patatas fritas" -> "patatas fritas"
            "pepinillo", "pepinillos" -> "pepinillo"
            "pepino", "pepinos" -> "pepino"
            "carne de perdiz", "perdiz" -> "carne de perdiz"
            "pimiento", "pimientos" -> "pimiento"
            "pimiento crudo", "pimientos crudos" -> "pimiento crudo"
            "pimiento a la plancha", "pimientos a la plancha" -> "pimiento a la plancha"
            "gelatina", "gelatinas" -> "gelatina"
            "golosina", "golosinas", "chuches", "gominolas" -> "golosina"
            "regaliz", "regalices" -> "regaliz"
            "salmón cocinado", "salmón ahumado" -> "salmón cocinado"
            "salmón crudo", "sasimi" -> "salmón crudo"
            "setas", "hongos" -> "setas"
            "setas boletus", "boletus" -> "setas boletus"
            "tarta", "tartas" -> "tarta"
            "tomate", "tomates" -> "tomate"
            "yogurt liquido", "yogurt de beber" -> "yogurt liquido"
            "zanahoria", "zanahorias" -> "zanahoria"
            "zanahoria cocinada", "zanahorias cocinadas" -> "zanahoria cocinada"



            // MEDICAMENTOS
            "antidoto", "antidotos" -> "antidoto"
            "analgesico", "analgesicos" -> "analgesico"
            "analgesico opioide", "analgesicos opioides" -> "analgesico opioide"
            "analgesico antipireptico", "analgesicos antipirepticos" -> "analgesico antipireptico"
            "antiepileptico", "antiepilepticos" -> "antiepileptico"
            "antiparkinsoniano", "antiparkinsonianos" -> "antiparkinsoniano"
            "ansiolitico", "ansioliticos" -> "ansiolitico"
            "antidepresivo", "antidepresivos" -> "antidepresivo"
            "sedante", "sedantes", "hipnotico", "hipnoticos" -> "sedante"
            "anestesico", "anestesicos" -> "anestesico"
            "anestesico local", "anestesicos locales" -> "anestesico local"
            "antiacido", "antiacidos" -> "antiacido"
            "antiulcero", "antiulceros", "protector gastrico", "protectores gastricos" -> "antiulcero"
            "diuretico", "diureticos" -> "diuretico"
            "mucloticos" -> "mucloticos"
            "antitusivo", "antitusivos" -> "antitusivo"
            "antidiabetico", "antiabetico", "antiabeticos" -> "antidiabetico"
            "antianemico", "antianemicos" -> "antianemico"
            "antibiotico", "antibioticos" -> "antibiotico"
            "antidiarreico", "antiarreico", "antiarreicos" -> "antidiarreico"
            "laxante", "laxantes" -> "laxante"
            "antiemetico", "antiemeticos" -> "antiemetico"
            "antifungico", "antifungicos" -> "antifungico"
            "antigotoso", "antigotosos" -> "antigotoso"
            "antihemorragico", "antihemorragicos" -> "antihemorragico"
            "antihistaminico", "antihistaminicos" -> "antihistaminico"
            "antiseptico", "antisepticos" -> "antiseptico"
            "desinfectante", "desinfectantes" -> "desinfectante"
            "antiinflamatorio", "antiinflamatorios" -> "antiinflamatorio"
            "antireumatico", "antireumaticos" -> "antireumatico"
            "tratamiento para la tuberculosis", "tratamientoa para la tuberculosis" -> "tratamiento para la tuberculosis"
            "antiaginoso", "antiaginosos" -> "antiaginoso"
            "antitrombotico", "antitromboticos" -> "antitrombotico"
            "trombolitico", "tromboliticos" -> "trombolitico"
            "antiagregante", "antiagregantes" -> "antiagregante"
            "antiviral", "antivirales" -> "antiviral"
            "antieespasmodico", "antieespasmodicos" -> "antieespasmodico"
            "corticoide", "corticoides" -> "corticoide"
            "hipolipemiante", "hipolipemiantes" -> "hipolipemiante"
            "relajante", "relajantes" -> "relajante"
            "relajante muscular", "relajantes musculares" -> "relajante muscular"
            "terapia tiroidea", "terapias tiroideas" -> "terapia tiroidea"
            "antiasmatico", "antiasmaticos" -> "antiasmatico"
            "broncodilatador", "broncodilatadores" -> "broncodilatador"
            "inductor de parto", "inductores de parto" -> "inductor de parto"
            "inhibidor de parto", "inhibidores de parto" -> "inhibidor de parto"
            "anticonceptivo", "anticonceptivos" -> "anticonceptivo"
            "factor vitaminico", "factor vitaminicos" -> "factor vitaminico"
            "cariotonico", "cardiotonicos" -> "cariotonico"
            "antiarrimicos" -> "antiarrimicos"
            "inmunosupresor", "inmunosupresores" -> "inmunosupresor"


            // SUCESOS
            "caida", "golpe", "caido", "golpeado" -> "golpe"



            else -> entrada
        }
    }
}
*/
fun obtenerTermino(entrada: String): String {
    return when (entrada) {

        // SINTOMAS
        "herida", "heridas" -> "herida"
        "dolor", "dolores", "daño" -> "dolor"
        "debilidad muscular", "debilidad" -> "debilidad"
        "problema de equilibrio", "falta de equilibrio", "problemas de equilibrio" -> "falta de equilibrio"
        "fiebre", "dolor de cabeza", "dolores de cabeza" -> "fiebre"
        "sudor nocturno", "sudores nocturnos" -> "sudor nocturno"
        "cambios sensoriales", "cambio sensorial" -> "cambios sensoriales"
        "sibilancia", "sibilancias" -> "sibilancia"
        "mareo", "vertigo" -> "mareo"
        "vomito", "vomitos", "nauseas" -> "vomito"
        "problema urinario", "problemas urinarios" -> "problema urinario"
        "dolor articular", "dolor en las articulaciones" -> "dolor articular"
        "cambio de temperatura", "cambios de temperatura" -> "cambio de temperatura"
        "confusion", "cambios de memoria" -> "confusion"
        "mareo", "mareos" -> "mareo"
        "síncope", "sincopes" -> "síncope"
        "vértigo", "vertigos" -> "vértigo"
        "cambios de animo", "cambio de animo", "cambio de humor", "cambios de humor" -> "cambios en el estado mental"
        "respiracion dificultosa", "dificultad respiratoria", "dificultades respiratorias" -> "respiración dificultosa"
        "sentimiento suicida", "sentimientos suicida" -> "sentimiento suicida"
        "sentimiento desesperanza", "desesperanza" -> "sentimiento de desesperanza"
        "llanto", "llantos" -> "llanto"
        "desmayo", "desmayos" -> "desmayo"
        "estado de animo deprimido", "depresion", "deprimido" -> "estado de ánimo deprimido"
        "aumento de energia", "aumentos de energia", "subidon de energia", "subidones de enrgia" -> "aumento de energía"
        "desconcentracion", "incapacidad para concentrarse" -> "desconcentracion"
        "fatiga", "cansancio" -> "fatiga"
        "bajada de peso", "bajadas de peso", "disminucion del peso", "disminución del peso corporal" -> "bajada de peso"
        "hipotonia muscular", "bajada muscular" -> "hipotonía muscular"
        "quemazon", "sensación de quemazón" -> "quemazon"
        "cólico abdominal", "colico abdominal", "colicos abdominales" -> "cólico abdominal"
        "midrasis", "pupilas dilatadas" -> "midriasis"
        "incontinencia urinaria de urgencia", "urgencias orinarias", "incontinencia urinaria", "incontinencia de urgencia" -> "incontinencia urinaria de urgencia"
        "disminucion de heces", "calibre disminuido de las heces" -> "disminucion de heces"
        "heces amarillas", "heces amarillentas", "color amarillo en las heces", "color amarillento en las heces", "Color de las heces amarillo" -> "heces amarillas"
        "sofoco", "sofocos" -> "sofoco"
        "dolor subito", "dolores subitos" -> "dolor subito"
        "zumbido en los oidos", "zumbidos en los oidos" -> "zumbido en los oídos"
        "calambres", "calambre" -> "calambres"
        "ahogo", "ahogamiento" -> "ahogo"
        "estornudos", "estornudos", "estornudo" -> "estornudos"
        "flatulencias", "flatulencia", "flatulencias" -> "flatulencias"


        // ZONAS
        "cara", "rostro" -> "cara"
        "ojos", "ojo" -> "ojos"
        "dientes", "diente" -> "dientes"
        "orejas", "oreja" -> "orejas"
        "hombros", "hombro" -> "hombros"
        "columna vertebral", "columna" -> "columna vertebral"
        "trapecio", "trapecios" -> "trapecio"
        "brazo", "brazos", "extremidades superiores" -> "brazo"
        "mano", "manos" -> "mano"
        "dedos", "dedo" -> "dedos"
        "piernas", "pierna", "extremidades inferiores" -> "piernas"
        "pulmones", "pulmón" -> "pulmones"
        "dedos", "dedo" -> "dedos"
        "pulgar", "dedo pulgar" -> "pulgar"
        "índice", "dedo índice" -> "índice"
        "medio", "dedo medio" -> "medio"
        "anular", "dedo anular" -> "anular"
        "meñique", "dedo meñique" -> "meñique"
        "uñas", "uña" -> "uñas"
        "pie", "pies" -> "pie"

        // ALIMENTOS
        "carne de caballo", "caballo" -> "carne de caballo"
        "carne de cabra", "cabra" -> "carne de cabra"
        "carne cabrito", "cabrito" -> "carne cabrito"
        "carne de cerdo", "cerdo" -> "carne de cerdo"
        "carne de conejo", "conejo" -> "carne de conejo"
        "carne de cordero", "cordero" -> "carne de cordero"
        "carne de res", "res" -> "carne de res"
        "carne de venado", "venado" -> "carne de venado"
        "carne de oveja", "oveja" -> "carne de oveja"
        "carne de ternera", "ternera" -> "carne de ternera"
        "carne de vaca", "vaca" -> "carne de vaca"
        "carne de pescado", "pescado" -> "carne de pescado"
        "carne de pescado blanco", "pescado blanco" -> "carne de pescado blanco"
        "carne de pescado azul", "pescado azul" -> "carne de pescado azul"
        "carne de pato", "pato" -> "carne de pato"
        "carne de pavo", "pavo" -> "carne de pavo"
        "carne de pollo", "pollo" -> "carne de pollo"
        "caldo de pollo", "caldo de pavo" -> "caldo de pollo"
        "cereales de arroz", "cereales de arroz inflado" -> "cereales de arroz"
        "chícharos", "chicharrones" -> "chícharos"
        "chocolate negro", "chocolate oscuro" -> "chocolate negro"
        "chocolate negro con almendras", "chocolate oscuro con almendras" -> "chocolate negro con almendras"
        "carne codorniz", "codorniz" -> "carne codorniz"
        "espárragos cocinados", "espárragos cocidos" -> "espárragos cocinados"
        "gambas cocinadas", "gambas cocidas" -> "gambas cocinadas"
        "hamburguesa", "hamburguesas" -> "hamburguesa"
        "hamburguesa vegana", "hamburguesas veganas" -> "hamburguesa vegana"
        "huevo crudo", "huevos crudos" -> "huevo crudo"
        "huevo frito", "huevos fritos" -> "huevo frito"
        "huevo cocido", "huevos cocidos" -> "huevo cocido"
        "yema de huevo", "yemas de huevo" -> "yema de huevo"
        "clara de huevo", "claras de huevo" -> "clara de huevo"
        "zumo", "zumos" -> "zumo"
        "embutido", "embutidos" -> "embutido"
        "patata", "patatas" -> "patata"
        "patata asada", "patatas asadas" -> "patata asada"
        "patatas fritas" -> "patatas fritas"
        "pepinillo", "pepinillos" -> "pepinillo"
        "pepino", "pepinos" -> "pepino"
        "carne de perdiz", "perdiz" -> "carne de perdiz"
        "pimiento", "pimientos" -> "pimiento"
        "pimiento crudo", "pimientos crudos" -> "pimiento crudo"
        "pimiento a la plancha", "pimientos a la plancha" -> "pimiento a la plancha"
        "gelatina", "gelatinas" -> "gelatina"
        "golosina", "golosinas", "chuches", "gominolas" -> "golosina"
        "regaliz", "regalices" -> "regaliz"
        "salmón cocinado", "salmón ahumado" -> "salmón cocinado"
        "salmón crudo", "sasimi" -> "salmón crudo"
        "setas", "hongos" -> "setas"
        "setas boletus", "boletus" -> "setas boletus"
        "tarta", "tartas" -> "tarta"
        "tomate", "tomates" -> "tomate"
        "yogurt liquido", "yogurt de beber" -> "yogurt liquido"
        "zanahoria", "zanahorias" -> "zanahoria"
        "zanahoria cocinada", "zanahorias cocinadas" -> "zanahoria cocinada"



        // MEDICAMENTOS
        "antidoto", "antidotos" -> "antidoto"
        "analgesico", "analgesicos" -> "analgesico"
        "analgesico opioide", "analgesicos opioides" -> "analgesico opioide"
        "analgesico antipireptico", "analgesicos antipirepticos" -> "analgesico antipireptico"
        "antiepileptico", "antiepilepticos" -> "antiepileptico"
        "antiparkinsoniano", "antiparkinsonianos" -> "antiparkinsoniano"
        "ansiolitico", "ansioliticos" -> "ansiolitico"
        "antidepresivo", "antidepresivos" -> "antidepresivo"
        "sedante", "sedantes", "hipnotico", "hipnoticos" -> "sedante"
        "anestesico", "anestesicos" -> "anestesico"
        "anestesico local", "anestesicos locales" -> "anestesico local"
        "antiacido", "antiacidos" -> "antiacido"
        "antiulcero", "antiulceros", "protector gastrico", "protectores gastricos" -> "antiulcero"
        "diuretico", "diureticos" -> "diuretico"
        "mucloticos" -> "mucloticos"
        "antitusivo", "antitusivos" -> "antitusivo"
        "antidiabetico", "antiabetico", "antiabeticos" -> "antidiabetico"
        "antianemico", "antianemicos" -> "antianemico"
        "antibiotico", "antibioticos" -> "antibiotico"
        "antidiarreico", "antiarreico", "antiarreicos" -> "antidiarreico"
        "laxante", "laxantes" -> "laxante"
        "antiemetico", "antiemeticos" -> "antiemetico"
        "antifungico", "antifungicos" -> "antifungico"
        "antigotoso", "antigotosos" -> "antigotoso"
        "antihemorragico", "antihemorragicos" -> "antihemorragico"
        "antihistaminico", "antihistaminicos" -> "antihistaminico"
        "antiseptico", "antisepticos" -> "antiseptico"
        "desinfectante", "desinfectantes" -> "desinfectante"
        "antiinflamatorio", "antiinflamatorios" -> "antiinflamatorio"
        "antireumatico", "antireumaticos" -> "antireumatico"
        "tratamiento para la tuberculosis", "tratamientoa para la tuberculosis" -> "tratamiento para la tuberculosis"
        "antiaginoso", "antiaginosos" -> "antiaginoso"
        "antitrombotico", "antitromboticos" -> "antitrombotico"
        "trombolitico", "tromboliticos" -> "trombolitico"
        "antiagregante", "antiagregantes" -> "antiagregante"
        "antiviral", "antivirales" -> "antiviral"
        "antieespasmodico", "antieespasmodicos" -> "antieespasmodico"
        "corticoide", "corticoides" -> "corticoide"
        "hipolipemiante", "hipolipemiantes" -> "hipolipemiante"
        "relajante", "relajantes" -> "relajante"
        "relajante muscular", "relajantes musculares" -> "relajante muscular"
        "terapia tiroidea", "terapias tiroideas" -> "terapia tiroidea"
        "antiasmatico", "antiasmaticos" -> "antiasmatico"
        "broncodilatador", "broncodilatadores" -> "broncodilatador"
        "inductor de parto", "inductores de parto" -> "inductor de parto"
        "inhibidor de parto", "inhibidores de parto" -> "inhibidor de parto"
        "anticonceptivo", "anticonceptivos" -> "anticonceptivo"
        "factor vitaminico", "factor vitaminicos" -> "factor vitaminico"
        "cariotonico", "cardiotonicos" -> "cariotonico"
        "antiarrimicos" -> "antiarrimicos"
        "inmunosupresor", "inmunosupresores" -> "inmunosupresor"


        // SUCESOS
        "caida", "golpe", "caido", "golpeado" -> "golpe"


        else -> entrada
    }
}