package furhatos.app.pacientehospital.utils
/*
class EntityHelper {

    fun obtenerTermino(entrada: String): String {
        return when (entrada) {

            // SINTOMAS
            "herida", "heridas" -> "herida"
            "dolor", "dolores", "daño" -> "dolor"
            "debilidad muscular", "debilidad" -> "debilidad"
            "problema de equilibrio", "falta de equilibrio", "problemas de equilibrio" -> "falta de equilibrio"
            "fiebre", "dolor de cabeza", "dolores de cabeza" -> "fiebre"
            "sudor nocturno", "sudores nocturnos" -> "sudor nocturno"
            "cambios sensoriales", "cambio sensorial" -> "cambios sensoriales"
            "sibilancia", "sibilancias" -> "sibilancia"
            "mareo", "vertigo" -> "mareo"
            "vomito", "vomitos", "nauseas" -> "vomito"
            "problema urinario", "problemas urinarios" -> "problema urinario"
            "dolor articular", "dolor en las articulaciones" -> "dolor articular"
            "cambio de temperatura", "cambios de temperatura" -> "cambio de temperatura"
            "confusion", "cambios de memoria" -> "confusion"
            "mareo", "mareos" -> "mareo"
            "síncope", "sincopes" -> "síncope"
            "vértigo", "vertigos" -> "vértigo"
            "cambios de animo", "cambio de animo", "cambio de humor", "cambios de humor" -> "cambios en el estado mental"
            "respiracion dificultosa", "dificultad respiratoria", "dificultades respiratorias" -> "respiración dificultosa"
            "sentimiento suicida", "sentimientos suicida" -> "sentimiento suicida"
            "sentimiento desesperanza", "desesperanza" -> "sentimiento de desesperanza"
            "llanto", "llantos" -> "llanto"
            "desmayo", "desmayos" -> "desmayo"
            "estado de animo deprimido", "depresion", "deprimido" -> "estado de ánimo deprimido"
            "aumento de energia", "aumentos de energia", "subidon de energia", "subidones de enrgia" -> "aumento de energía"
            "desconcentracion", "incapacidad para concentrarse" -> "desconcentracion"
            "fatiga", "cansancio" -> "fatiga"
            "bajada de peso", "bajadas de peso", "disminucion del peso", "disminución del peso corporal" -> "bajada de peso"
            "hipotonia muscular", "bajada muscular" -> "hipotonía muscular"
            "quemazon", "sensación de quemazón" -> "quemazon"
            "cólico abdominal", "colico abdominal", "colicos abdominales" -> "cólico abdominal"
            "midrasis", "pupilas dilatadas" -> "midriasis"
            "incontinencia urinaria de urgencia", "urgencias orinarias", "incontinencia urinaria", "incontinencia de urgencia" -> "incontinencia urinaria de urgencia"
            "disminucion de heces", "calibre disminuido de las heces" -> "disminucion de heces"
            "heces amarillas", "heces amarillentas", "color amarillo en las heces", "color amarillento en las heces", "Color de las heces amarillo" -> "heces amarillas"
            "sofoco", "sofocos" -> "sofoco"
            "dolor subito", "dolores subitos" -> "dolor subito"
            "zumbido en los oidos", "zumbidos en los oidos" -> "zumbido en los oídos"
            "calambres", "calambre" -> "calambres"
            "ahogo", "ahogamiento" -> "ahogo"
            "estornudos", "estornudos", "estornudo" -> "estornudos"
            "flatulencias", "flatulencia", "flatulencias" -> "flatulencias"


            // ZONAS
            "cara", "rostro" -> "cara"
            "ojos", "ojo" -> "ojos"
            "dientes", "diente" -> "dientes"
            "orejas", "oreja" -> "orejas"
            "hombros", "hombro" -> "hombros"
            "columna vertebral", "columna" -> "columna vertebral"
            "trapecio", "trapecios" -> "trapecio"
            "brazo", "brazos", "extremidades superiores" -> "brazo"
            "mano", "manos" -> "mano"
            "dedos", "dedo" -> "dedos"
            "piernas", "pierna", "extremidades inferiores" -> "piernas"
            "pulmones", "pulmón" -> "pulmones"
            "dedos", "dedo" -> "dedos"
            "pulgar", "dedo pulgar" -> "pulgar"
            "índice", "dedo índice" -> "índice"
            "medio", "dedo medio" -> "medio"
            "anular", "dedo anular" -> "anular"
            "meñique", "dedo meñique" -> "meñique"
            "uñas", "uña" -> "uñas"
            "pie", "pies" -> "pie"

            // ALIMENTOS
            "carne de caballo", "caballo" -> "carne de caballo"
            "carne de cabra", "cabra" -> "carne de cabra"
            "carne cabrito", "cabrito" -> "carne cabrito"
            "carne de cerdo", "cerdo" -> "carne de cerdo"
            "carne de conejo", "conejo" -> "carne de conejo"
            "carne de cordero", "cordero" -> "carne de cordero"
            "carne de res", "res" -> "carne de res"
            "carne de venado", "venado" -> "carne de venado"
            "carne de oveja", "oveja" -> "carne de oveja"
            "carne de ternera", "ternera" -> "carne de ternera"
            "carne de vaca", "vaca" -> "carne de vaca"
            "carne de pescado", "pescado" -> "carne de pescado"
            "carne de pescado blanco", "pescado blanco" -> "carne de pescado blanco"
            "carne de pescado azul", "pescado azul" -> "carne de pescado azul"
            "carne de pato", "pato" -> "carne de pato"
            "carne de pavo", "pavo" -> "carne de pavo"
            "carne de pollo", "pollo" -> "carne de pollo"
            "caldo de pollo", "caldo de pavo" -> "caldo de pollo"
            "cereales de arroz", "cereales de arroz inflado" -> "cereales de arroz"
            "chícharos", "chicharrones" -> "chícharos"
            "chocolate negro", "chocolate oscuro" -> "chocolate negro"
            "chocolate negro con almendras", "chocolate oscuro con almendras" -> "chocolate negro con almendras"
            "carne codorniz", "codorniz" -> "carne codorniz"
            "espárragos cocinados", "espárragos cocidos" -> "espárragos cocinados"
            "gambas cocinadas", "gambas cocidas" -> "gambas cocinadas"
            "hamburguesa", "hamburguesas" -> "hamburguesa"
            "hamburguesa vegana", "hamburguesas veganas" -> "hamburguesa vegana"
            "huevo crudo", "huevos crudos" -> "huevo crudo"
            "huevo frito", "huevos fritos" -> "huevo frito"
            "huevo cocido", "huevos cocidos" -> "huevo cocido"
            "yema de huevo", "yemas de huevo" -> "yema de huevo"
            "clara de huevo", "claras de huevo" -> "clara de huevo"
            "zumo", "zumos" -> "zumo"
            "embutido", "embutidos" -> "embutido"
            "patata", "patatas" -> "patata"
            "patata asada", "patatas asadas" -> "patata asada"
            "patatas fritas" -> "patatas fritas"
            "pepinillo", "pepinillos" -> "pepinillo"
            "pepino", "pepinos" -> "pepino"
            "carne de perdiz", "perdiz" -> "carne de perdiz"
            "pimiento", "pimientos" -> "pimiento"
            "pimiento crudo", "pimientos crudos" -> "pimiento crudo"
            "pimiento a la plancha", "pimientos a la plancha" -> "pimiento a la plancha"
            "gelatina", "gelatinas" -> "gelatina"
            "golosina", "golosinas", "chuches", "gominolas" -> "golosina"
            "regaliz", "regalices" -> "regaliz"
            "salmón cocinado", "salmón ahumado" -> "salmón cocinado"
            "salmón crudo", "sasimi" -> "salmón crudo"
            "setas", "hongos" -> "setas"
            "setas boletus", "boletus" -> "setas boletus"
            "tarta", "tartas" -> "tarta"
            "tomate", "tomates" -> "tomate"
            "yogurt liquido", "yogurt de beber" -> "yogurt liquido"
            "zanahoria", "zanahorias" -> "zanahoria"
            "zanahoria cocinada", "zanahorias cocinadas" -> "zanahoria cocinada"



            // MEDICAMENTOS
            "antidoto", "antidotos" -> "antidoto"
            "analgesico", "analgesicos" -> "analgesico"
            "analgesico opioide", "analgesicos opioides" -> "analgesico opioide"
            "analgesico antipireptico", "analgesicos antipirepticos" -> "analgesico antipireptico"
            "antiepileptico", "antiepilepticos" -> "antiepileptico"
            "antiparkinsoniano", "antiparkinsonianos" -> "antiparkinsoniano"
            "ansiolitico", "ansioliticos" -> "ansiolitico"
            "antidepresivo", "antidepresivos" -> "antidepresivo"
            "sedante", "sedantes", "hipnotico", "hipnoticos" -> "sedante"
            "anestesico", "anestesicos" -> "anestesico"
            "anestesico local", "anestesicos locales" -> "anestesico local"
            "antiacido", "antiacidos" -> "antiacido"
            "antiulcero", "antiulceros", "protector gastrico", "protectores gastricos" -> "antiulcero"
            "diuretico", "diureticos" -> "diuretico"
            "mucloticos" -> "mucloticos"
            "antitusivo", "antitusivos" -> "antitusivo"
            "antidiabetico", "antiabetico", "antiabeticos" -> "antidiabetico"
            "antianemico", "antianemicos" -> "antianemico"
            "antibiotico", "antibioticos" -> "antibiotico"
            "antidiarreico", "antiarreico", "antiarreicos" -> "antidiarreico"
            "laxante", "laxantes" -> "laxante"
            "antiemetico", "antiemeticos" -> "antiemetico"
            "antifungico", "antifungicos" -> "antifungico"
            "antigotoso", "antigotosos" -> "antigotoso"
            "antihemorragico", "antihemorragicos" -> "antihemorragico"
            "antihistaminico", "antihistaminicos" -> "antihistaminico"
            "antiseptico", "antisepticos" -> "antiseptico"
            "desinfectante", "desinfectantes" -> "desinfectante"
            "antiinflamatorio", "antiinflamatorios" -> "antiinflamatorio"
            "antireumatico", "antireumaticos" -> "antireumatico"
            "tratamiento para la tuberculosis", "tratamientoa para la tuberculosis" -> "tratamiento para la tuberculosis"
            "antiaginoso", "antiaginosos" -> "antiaginoso"
            "antitrombotico", "antitromboticos" -> "antitrombotico"
            "trombolitico", "tromboliticos" -> "trombolitico"
            "antiagregante", "antiagregantes" -> "antiagregante"
            "antiviral", "antivirales" -> "antiviral"
            "antieespasmodico", "antieespasmodicos" -> "antieespasmodico"
            "corticoide", "corticoides" -> "corticoide"
            "hipolipemiante", "hipolipemiantes" -> "hipolipemiante"
            "relajante", "relajantes" -> "relajante"
            "relajante muscular", "relajantes musculares" -> "relajante muscular"
            "terapia tiroidea", "terapias tiroideas" -> "terapia tiroidea"
            "antiasmatico", "antiasmaticos" -> "antiasmatico"
            "broncodilatador", "broncodilatadores" -> "broncodilatador"
            "inductor de parto", "inductores de parto" -> "inductor de parto"
            "inhibidor de parto", "inhibidores de parto" -> "inhibidor de parto"
            "anticonceptivo", "anticonceptivos" -> "anticonceptivo"
            "factor vitaminico", "factor vitaminicos" -> "factor vitaminico"
            "cariotonico", "cardiotonicos" -> "cariotonico"
            "antiarrimicos" -> "antiarrimicos"
            "inmunosupresor", "inmunosupresores" -> "inmunosupresor"


            // SUCESOS
            "caida", "golpe", "caido", "golpeado" -> "golpe"



            else -> entrada
        }
    }
}
*/
fun obtenerTermino(entrada: String): String {
    return when (entrada) {



        // SINTOMAS
        "herida", "heridas" -> "herida"
        "dolor", "dolores", "daño" -> "dolor"
        "debilidad muscular", "debilidad" -> "debilidad"
        "problema de equilibrio", "falta de equilibrio", "problemas de equilibrio" -> "falta de equilibrio"
        "fiebre", "dolor de cabeza", "dolores de cabeza" -> "fiebre"
        "sudor nocturno", "sudores nocturnos" -> "sudor nocturno"
        "cambios sensoriales", "cambio sensorial" -> "cambios sensoriales"
        "sibilancia", "sibilancias" -> "sibilancia"
        "mareo", "vertigo" -> "mareo"
        "vomito", "vomitos", "nauseas" -> "vomito"
        "problema urinario", "problemas urinarios" -> "problema urinario"
        "dolor articular", "dolor en las articulaciones" -> "dolor articular"
        "cambio de temperatura", "cambios de temperatura" -> "cambio de temperatura"
        "confusion", "cambios de memoria" -> "confusion"
        "mareo", "mareos" -> "mareo"
        "síncope", "sincopes" -> "síncope"
        "vértigo", "vertigos" -> "vértigo"
        "cambios de animo", "cambio de animo", "cambio de humor", "cambios de humor" -> "cambios en el estado mental"
        "respiracion dificultosa", "dificultad respiratoria", "dificultades respiratorias" -> "respiración dificultosa"
        "sentimiento suicida", "sentimientos suicida" -> "sentimiento suicida"
        "sentimiento desesperanza", "desesperanza" -> "sentimiento de desesperanza"
        "llanto", "llantos" -> "llanto"
        "desmayo", "desmayos" -> "desmayo"
        "estado de animo deprimido", "depresion", "deprimido" -> "estado de ánimo deprimido"
        "aumento de energia", "aumentos de energia", "subidon de energia", "subidones de enrgia" -> "aumento de energía"
        "desconcentracion", "incapacidad para concentrarse" -> "desconcentracion"
        "fatiga", "cansancio" -> "fatiga"
        "bajada de peso", "bajadas de peso", "disminucion del peso", "disminución del peso corporal" -> "bajada de peso"
        "hipotonia muscular", "bajada muscular" -> "hipotonía muscular"
        "quemazon", "sensación de quemazón" -> "quemazon"
        "cólico abdominal", "colico abdominal", "colicos abdominales" -> "cólico abdominal"
        "midrasis", "pupilas dilatadas" -> "midriasis"
        "incontinencia urinaria de urgencia", "urgencias orinarias", "incontinencia urinaria", "incontinencia de urgencia" -> "incontinencia urinaria de urgencia"
        "disminucion de heces", "calibre disminuido de las heces" -> "disminucion de heces"
        "heces amarillas", "heces amarillentas", "color amarillo en las heces", "color amarillento en las heces", "Color de las heces amarillo" -> "heces amarillas"
        "sofoco", "sofocos" -> "sofoco"
        "dolor subito", "dolores subitos" -> "dolor subito"
        "zumbido en los oidos", "zumbidos en los oidos" -> "zumbido en los oídos"
        "calambres", "calambre" -> "calambres"
        "ahogo", "ahogamiento" -> "ahogo"
        "estornudos", "estornudos", "estornudo" -> "estornudos"
        "flatulencias", "flatulencia", "flatulencias" -> "flatulencias"


        // ZONAS
        "cara", "rostro" -> "cara"
        "ojos", "ojo" -> "ojos"
        "dientes", "diente" -> "dientes"
        "orejas", "oreja" -> "orejas"
        "hombros", "hombro" -> "hombros"
        "columna vertebral", "columna" -> "columna vertebral"
        "trapecio", "trapecios" -> "trapecio"
        "brazo", "brazos", "extremidades superiores" -> "brazo"
        "mano", "manos" -> "mano"
        "dedos", "dedo" -> "dedos"
        "piernas", "pierna", "extremidades inferiores" -> "piernas"
        "pulmones", "pulmón" -> "pulmones"
        "dedos", "dedo" -> "dedos"
        "pulgar", "dedo pulgar" -> "pulgar"
        "índice", "dedo índice" -> "índice"
        "medio", "dedo medio" -> "medio"
        "anular", "dedo anular" -> "anular"
        "meñique", "dedo meñique" -> "meñique"
        "uñas", "uña" -> "uñas"
        "pie", "pies" -> "pie"

        // ALIMENTOS
        "Proteínas", "proteinas", "alimentos ricos en proteinas" -> "Proteínas"
        "Carbohidratos", "carbohidratos", "alimentos ricos en carbohidratos" -> "Carbohidratos"
        "Grasas", "grasas", "alimentos ricos en grasas" -> "Grasas"
        "Fibra dietética", "fibra dietética", "alimentos ricos en fibra dietética" -> "Fibra dietética"
        "Vitaminas", "vitaminas", "alimentos ricos en vitaminas" -> "Vitaminas"
        "Minerales", "minerales", "alimentos ricos en minerales" -> "Minerales"
        "Ácidos grasos", "ácidos grasos", "alimentos ricos en ácidos grasos" -> "Ácidos grasos"
        "Antioxidantes", "antioxidantes", "alimentos ricos en antioxidantes" -> "Antioxidantes"
        "Aminoácidos esenciales", "aminoácidos esenciales", "alimentos ricos en aminoácidos esenciales" -> "Aminoácidos esenciales"
        "Sal", "sal", "alimentos ricos en sal" -> "Sal"
        "Azúcar", "azúcar", "alimentos ricos en azúcar" -> "Azúcar"
        "Micronutrientes", "micronutrientes", "alimentos ricos en micronutrientes" -> "Micronutrientes"
        "Vitamina A", "vitamina A", "alimentos ricos en vitamina A" -> "Vitamina A"
        "Vitamina B", "vitamina B", "alimentos ricos en vitamina B" -> "Vitamina B"
        "Vitamina C", "vitamina C", "alimentos ricos en vitamina C" -> "Vitamina C"
        "Vitamina D", "vitamina D", "alimentos ricos en vitamina D" -> "Vitamina D"
        "Vitamina E", "vitamina E", "alimentos ricos en vitamina E" -> "Vitamina E"
        "Vitamina K", "vitamina K", "alimentos ricos en vitamina K" -> "Vitamina K"
        "Zinc", "zinc", "alimentos ricos en zinc" -> "Zinc"
        "Cobre", "cobre", "alimentos ricos en cobre" -> "Cobre"
        "Yodo", "yodo", "alimentos ricos en yodo" -> "Yodo"
        "Hierro", "hierro", "alimentos ricos en hierro" -> "Hierro"
        "Selenio", "selenio", "alimentos ricos en selenio" -> "Selenio"
        "Cromo", "cromo", "alimentos ricos en cromo" -> "Cromo"
        "Flúor", "flúor", "alimentos ricos en flúor" -> "Flúor"
        "Calcio", "calcio", "alimentos ricos en calcio" -> "Calcio"
        "Fósforo", "fósforo", "alimentos ricos en fósforo" -> "Fósforo"
        "Magnesio", "magnesio", "alimentos ricos en magnesio" -> "Magnesio"

        "carne de caballo", "caballo" -> "carne de caballo"
        "carne de cabra", "cabra" -> "carne de cabra"
        "carne cabrito", "cabrito" -> "carne cabrito"
        "carne de cerdo", "cerdo" -> "carne de cerdo"
        "carne de conejo", "conejo" -> "carne de conejo"
        "carne de cordero", "cordero" -> "carne de cordero"
        "carne de res", "res" -> "carne de res"
        "carne de venado", "venado" -> "carne de venado"
        "carne de oveja", "oveja" -> "carne de oveja"
        "carne de ternera", "ternera" -> "carne de ternera"
        "carne de vaca", "vaca" -> "carne de vaca"
        "carne de pescado", "pescado" -> "carne de pescado"
        "carne de pescado blanco", "pescado blanco" -> "carne de pescado blanco"
        "carne de pescado azul", "pescado azul" -> "carne de pescado azul"
        "carne de pato", "pato" -> "carne de pato"
        "carne de pavo", "pavo" -> "carne de pavo"
        "carne de pollo", "pollo" -> "carne de pollo"
        "caldo de pollo", "caldo de pavo" -> "caldo de pollo"
        "cereales de arroz", "cereales de arroz inflado" -> "cereales de arroz"
        "chícharos", "chicharrones" -> "chícharos"
        "chocolate negro", "chocolate oscuro" -> "chocolate negro"
        "chocolate negro con almendras", "chocolate oscuro con almendras" -> "chocolate negro con almendras"
        "carne codorniz", "codorniz" -> "carne codorniz"
        "espárragos cocinados", "espárragos cocidos" -> "espárragos cocinados"
        "gambas cocinadas", "gambas cocidas" -> "gambas cocinadas"
        "hamburguesa", "hamburguesas" -> "hamburguesa"
        "hamburguesa vegana", "hamburguesas veganas" -> "hamburguesa vegana"
        "huevo crudo", "huevos crudos" -> "huevo crudo"
        "huevo frito", "huevos fritos" -> "huevo frito"
        "huevo cocido", "huevos cocidos" -> "huevo cocido"
        "yema de huevo", "yemas de huevo" -> "yema de huevo"
        "clara de huevo", "claras de huevo" -> "clara de huevo"
        "zumo", "zumos" -> "zumo"
        "embutido", "embutidos" -> "embutido"
        "patata", "patatas" -> "patata"
        "patata asada", "patatas asadas" -> "patata asada"
        "patatas fritas" -> "patatas fritas"
        "pepinillo", "pepinillos" -> "pepinillo"
        "pepino", "pepinos" -> "pepino"
        "carne de perdiz", "perdiz" -> "carne de perdiz"
        "pimiento", "pimientos" -> "pimiento"
        "pimiento crudo", "pimientos crudos" -> "pimiento crudo"
        "pimiento a la plancha", "pimientos a la plancha" -> "pimiento a la plancha"
        "gelatina", "gelatinas" -> "gelatina"
        "golosina", "golosinas", "chuches", "gominolas" -> "golosina"
        "regaliz", "regalices" -> "regaliz"
        "salmón cocinado", "salmón ahumado" -> "salmón cocinado"
        "salmón crudo", "sasimi" -> "salmón crudo"
        "setas", "hongos" -> "setas"
        "setas boletus", "boletus" -> "setas boletus"
        "tarta", "tartas" -> "tarta"
        "tomate", "tomates" -> "tomate"
        "yogurt liquido", "yogurt de beber" -> "yogurt liquido"
        "zanahoria", "zanahorias" -> "zanahoria"
        "zanahoria cocinada", "zanahorias cocinadas" -> "zanahoria cocinada"



        // MEDICAMENTOS
        "antidoto", "antidotos" -> "antidoto"
        "analgesico", "analgesicos" -> "analgesico"
        "analgesico opioide", "analgesicos opioides" -> "analgesico opioide"
        "analgesico antipireptico", "analgesicos antipirepticos" -> "analgesico antipireptico"
        "antiepileptico", "antiepilepticos" -> "antiepileptico"
        "antiparkinsoniano", "antiparkinsonianos" -> "antiparkinsoniano"
        "ansiolitico", "ansioliticos" -> "ansiolitico"
        "antidepresivo", "antidepresivos" -> "antidepresivo"
        "sedante", "sedantes", "hipnotico", "hipnoticos" -> "sedante"
        "anestesico", "anestesicos" -> "anestesico"
        "anestesico local", "anestesicos locales" -> "anestesico local"
        "antiacido", "antiacidos" -> "antiacido"
        "antiulcero", "antiulceros", "protector gastrico", "protectores gastricos" -> "antiulcero"
        "diuretico", "diureticos" -> "diuretico"
        "mucloticos" -> "mucloticos"
        "antitusivo", "antitusivos" -> "antitusivo"
        "antidiabetico", "antiabetico", "antiabeticos" -> "antidiabetico"
        "antianemico", "antianemicos" -> "antianemico"
        "antibiotico", "antibioticos" -> "antibiotico"
        "antidiarreico", "antiarreico", "antiarreicos" -> "antidiarreico"
        "laxante", "laxantes" -> "laxante"
        "antiemetico", "antiemeticos" -> "antiemetico"
        "antifungico", "antifungicos" -> "antifungico"
        "antigotoso", "antigotosos" -> "antigotoso"
        "antihemorragico", "antihemorragicos" -> "antihemorragico"
        "antihistaminico", "antihistaminicos" -> "antihistaminico"
        "antiseptico", "antisepticos" -> "antiseptico"
        "desinfectante", "desinfectantes" -> "desinfectante"
        "antiinflamatorio", "antiinflamatorios" -> "antiinflamatorio"
        "antireumatico", "antireumaticos" -> "antireumatico"
        "tratamiento para la tuberculosis", "tratamientoa para la tuberculosis" -> "tratamiento para la tuberculosis"
        "antiaginoso", "antiaginosos" -> "antiaginoso"
        "antitrombotico", "antitromboticos" -> "antitrombotico"
        "trombolitico", "tromboliticos" -> "trombolitico"
        "antiagregante", "antiagregantes" -> "antiagregante"
        "antiviral", "antivirales" -> "antiviral"
        "antieespasmodico", "antieespasmodicos" -> "antieespasmodico"
        "corticoide", "corticoides" -> "corticoide"
        "hipolipemiante", "hipolipemiantes" -> "hipolipemiante"
        "relajante", "relajantes" -> "relajante"
        "relajante muscular", "relajantes musculares" -> "relajante muscular"
        "terapia tiroidea", "terapias tiroideas" -> "terapia tiroidea"
        "antiasmatico", "antiasmaticos" -> "antiasmatico"
        "broncodilatador", "broncodilatadores" -> "broncodilatador"
        "inductor de parto", "inductores de parto" -> "inductor de parto"
        "inhibidor de parto", "inhibidores de parto" -> "inhibidor de parto"
        "anticonceptivo", "anticonceptivos" -> "anticonceptivo"
        "factor vitaminico", "factor vitaminicos" -> "factor vitaminico"
        "cariotonico", "cardiotonicos" -> "cariotonico"
        "antiarrimicos" -> "antiarrimicos"
        "inmunosupresor", "inmunosupresores" -> "inmunosupresor"


        //HABITOS

        "deporte", "practicar deporte", "practicas deporte", "actividad fisica", "actividad fisica" -> "deporte"
        "trabajar", "trabajas", "trabajo", "trabaja" -> "trabajar"
        "comer", "comes" -> "comer"
        "dormir", "duermes", "duerme" -> "dormir"
        "beber agua", "bebes agua" -> "beber agua"
        "asearse", "bañarse", "te bañas", "bañarte", "ducharte", "asearte", "te aseas" -> "asearse"
        "cepillarse los dientes", "cepillarte los dientes", "cepillar los dientes", "cepilla los dientes" -> "cepillarse los dientes"
        "lavarse las manos", "lavarte las manos", "te lavas las manos", "se lava las manos" -> "lavarse las manos"
        "hacer chequeos médicos", "haces chequeos médicos" -> "hacer chequeos médicos"
        "mantener buena postura", "mantener una buena postura", "mantienes una buena postura" -> "mantener buena postura"

        "estar en reposo", "estas en reposo" -> "estar en reposo"
        "estar sentado", "estar sentada", "estas sentado", "estas sentada" -> "estar sentado"
        "estar tumbado", "estar tumbada", "estas tumbado", "estas tumbada" -> "estar tumbado"
        "caminar", "caminas" -> "caminar"
        "correr", "corres" -> "correr"
        "subir escaleras", "subes escaleras" -> "subir escaleras"
        "esforzarse", "hacer esfuerzo", "haces esfuerzo", "esfuerzas", "te esfuerzas", "haces esfuerzos", "hace esfuerzos", "esfuerzo", "esfuerzos", "esfuerzo fisico" -> "esforzarse"
        "mover la articulacion", "mover las articulaciones", "hacer movimientos de articulaciones" -> "mover la articulacion"
        "hablar", "hablas" -> "hablar"
        "reirse", "se rie", "te ries", "reir" -> "reirse"
        "orinar", "mear", "orinas", "meas", "orina", "mea" -> "orinar"
        "defecar", "cagar", "defecas", "defeca", "cagas", "caga" -> "defecar"
        "tener relaciones", "tienes relaciones", "relaciones", "relaciones intimas", "relaciones sexuales", "coito" -> "tener relaciones"
        "mover la lengua", "mueves la lengua" -> "mover la lengua"
        "Mover los brazos", "mueves los brazos" -> "Mover los brazos"
        "Mover las piernas", "mueves las piernas" -> "Mover las piernas"
        "Mover los dedos", "mueves los dedos" -> "Mover los dedos"
        "Mover los pies", "mueves los pies" -> "Mover los pies"
        "Mover la cabeza", "mueves la cabeza" -> "Mover la cabeza"
        "Mover los hombros", "mueves los hombros" -> "Mover los hombros"
        "Mover las manos", "mueves las manos" -> "Mover las manos"
        "Mover los ojos", "mueves los ojos" -> "Mover los ojos"
        "Mover la cintura", "mueves la cintura" -> "Mover la cintura"
        "Mover las rodillas", "mueves las rodillas" -> "Mover las rodillas"
        "Mover los codos", "mueves los codos" -> "Mover los codos"
        "Mover los tobillos", "mueves los tobillos" -> "Mover los tobillos"
        "Mover los dedos de los pies", "mueves los dedos de los pies" -> "Mover los dedos de los pies"

        "pantalla", "estar frente a una pantalla", "estar frente a la pantalla", "estas frente a una pantalla", "estas frente a la pantalla" -> "pantalla"
        "cafe", "tomar cafe", "tomas cafe", "consumir cafe", "consumes cafe" -> "cafe"
        "alcohol", "beber alcohol", "bebes alcohol" -> "alcohol"
        "fumar", "fumas" -> "fumar"
        "siesta", "echar la siesta", "echas la siesta", "hacer siestas", "tomar una siesta", "tomas la siesta", "tomas siestas" -> "siesta"
        "trabajar", "trabajas" -> "trabajar"
        "estudiar", "estudias" -> "estudiar"
        "limpiar la casa", "limpias la casa" -> "limpiar la casa"
        "hacer la cama", "haces la cama" -> "hacer la cama"
        "cocinar", "cocinas" -> "cocinar"
        "ir de compras", "vas de compras" -> "ir de compras"
        "conducir", "conduces" -> "conducir"
        "usar el transporte público", "usas el transporte público" -> "usar el transporte público"
        "leer", "lees" -> "leer"
        "ver televisión", "ves televisión" -> "ver televisión"
        "escuchar música", "escuchas música" -> "escuchar música"
        "hablar por teléfono", "hablas por teléfono" -> "hablar por teléfono"
        "revisar las redes sociales", "revisas las redes sociales" -> "revisar las redes sociales"
        "hacer ejercicio", "haces ejercicio" -> "hacer ejercicio"
        "meditar", "meditas" -> "meditar"
        "practicar yoga", "practicas yoga" -> "practicar yoga"
        "correr", "corres" -> "correr"
        "caminar", "caminas" -> "caminar"
        "nadar", "nadas" -> "nadar"
        "andar en bicicleta", "andas en bicicleta" -> "andar en bicicleta"
        "hacer estiramientos", "haces estiramientos" -> "hacer estiramientos"
        "practicar la respiración profunda", "practicas la respiración profunda" -> "practicar la respiración profunda"
        "ir al gimnasio", "vas al gimnasio" -> "ir al gimnasio"
        "hacer senderismo", "haces senderismo" -> "hacer senderismo"
        "hacer escalada", "haces escalada" -> "hacer escalada"
        "baile", "bailas" -> "baile"
        "planificar el día", "planificas el día" -> "planificar el día"
        "hacer listas de tareas", "haces listas de tareas" -> "hacer listas de tareas"
        "usar una agenda", "usas una agenda" -> "usar una agenda"
        "participar en reuniones", "participas en reuniones" -> "participar en reuniones"
        "metas", "establecer metas", "estableces metas", "tienes metas" -> "metas"
        "descansar", "hacer descansos", "haces descansos", "descansas" -> "descansar"
        "organizar el espacio de trabajo", "organizas el espacio de trabajo", "organizar tu espacio de trabajo", "organizas tu espacio de trabajo" -> "organizar el espacio de trabajo"
        "aprender nuevas habilidades", "aprendes nuevas habilidades", "aprender habilidades nuevas", "aprendes habilidades nuevas" -> "aprender nuevas habilidades"
        "aprender nuevas cosas", "aprendes nuevas cosas", "aprender cosas nuevas", "aprendes cosas nuevas" -> "aprender nuevas cosas"
        "escribir", "escribes" -> "escribir"
        "salir con amigos", "sales con amigos" -> "salir con amigos"
        "tener citas", "tienes citas" -> "tener citas"
        "pasar tiempo en familia", "pasas tiempo en familia" -> "pasar tiempo en familia"
        "jugar videojuegos", "juegas videojuegos" -> "jugar videojuegos"
        "ir al cine", "vas al cine" -> "ir al cine"
        "jugar juegos de mesa", "juegas juegos de mesa" -> "jugar juegos de mesa"
        "viajar", "viajas" -> "viajar"
        "acampar", "acampas" -> "acampar"
        "dibujar", "dibujas" -> "dibujar"
        "pintar", "pintas" -> "pintar"
        "cantar", "cantas" -> "cantar"
        "fotografía", "fotografías" -> "fotografía"
        "bloguear", "blogueas" -> "bloguear"
        "pescar", "pescas" -> "pescar"
        "cazar", "cazas" -> "cazar"
        "hacer puzzles", "haces puzzles" -> "hacer puzzles"
        "jugar al ajedrez", "juegas al ajedrez" -> "jugar al ajedrez"
        "practicar la gratitud", "practicas la gratitud" -> "practicar la gratitud"
        "llevar un diario", "llevas un diario", "journaling" -> "llevar un diario"
        "fútbol", "jugar al fútbol", "juegas al fútbol" -> "fútbol"


        else -> entrada
    }
}